// // const mp=require("./first")
// // const mix=require("./calc")
// const read=require("./filehandling/main")
// // const rx=require("./filehandling/folder1/exa")
// // console.log(mix)
// // console.log("hello",mp)
// read.readDataFromFile()
// // console.log(read.createfolder())
// // console.log(rx.readexa())
// console.log("meet")